# **MÓDULO 14 - Exercício**
# Pré Processamento dos Dados - A primeira etapa Pré Modelagem

Para nossa atividade usaremos uma base de churn também, porém essa base não diz respeito a serviços bancários e sim serviços de internet, telefone e tv - Telecomunicação.

Vamos realizar aqui as etapas de limpeza e tratamento de dados vistos durante a aula, porém aplicados a essa base nova.

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Lembrem-se sempre de alterar a importação dos dados de acordo com o diretório de vocês.
df = pd.read_csv("CHURN_TELECON_MOD08_TAREFA.csv", delimiter=';')

df.head(10)

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes
5,9305-CDSKC,NaN,0,No,No,8,Yes,Fiber optic,No,No,Yes,Month-to-month,Electronic check,NaN,820.50,NaN
6,1452-KIOVK,NaN,0,No,Yes,22,Yes,Fiber optic,No,No,Yes,Month-to-month,Credit card (automatic),NaN,1949.40,NaN
7,6713-OKOMC,NaN,0,No,No,10,No,DSL,Yes,No,No,Month-to-month,Mailed check,NaN,301.90,NaN
8,7892-POOKP,NaN,0,Yes,No,28,Yes,Fiber optic,No,Yes,Yes,Month-to-month,Electronic check,NaN,3046.05,NaN
9,6388-TABGU,NaN,0,No,Yes,62,Yes,dsl,Yes,No,No,One year,Bank transfer (automatic),NaN,3487.95,NaN

Legenda dos dados:

*   **CustomerID** : Esse é o ID único de cada cliente nosso da rede de produtos de telecomunicação.

*   **Genero** : O genero dos nossos clientes.

*   **Idoso** : Se nosso cliente tem acima de 60 anos ou não. (Sim = 1 | Não = 0)

*   **Casado** : Se nosso cliente é casado ou não.

*   **Dependents** : Se cliente tem dependentes.

*   **Tempo_como_Cliente** : Tempo em meses que nosso cliente está com a nossa empresa.

*   **PhoneService** : Se ele contratou serviço telefônico com a nossa empresa.

*   **Servico_Internet** : Qual o tipo de serviço de internet contratado.

*   **Servico_Seguranca** : Se ele contratou serviço de segurança com a nossa empresa.

*   **Suporte_Tecnico** : Se já acionou o suporte técnico.

*   **StreamingTV** : Se ele contratou serviço de streaming para TV.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **Tipo_Contrato** : Qual o tipo de contrato dos nossos clientes, se era mensal, anual etc.

*   **PaymentMethod** : Forma de Pagamento.

*   **Pagamento_Mensal** : Quanto o cliente pagava mensalmente.

*   **Total_Pago** : Total já pago pelo cliente para nossa companhia.

*   **Churn** : Nossa coluna mais importante, se nosso cliente nos abandonou ou não.

# 1 - Carregue a base, verifique se os tipos de dados estão de acordo com cada coluna e caso não estejam realize a transformação dos tipos de dados.

In [ ]:
# 1. Verificando o estado atual dos tipos de dados e o uso de memória
print("--- Tipos de Dados e Uso de Memória (ANTES da Otimização) ---")
display(df.info())

# 2. Transformação de dados: Otimizando os tipos (Nível Avançado)
# Lista de colunas que representam categorias limitadas
colunas_categoricas = ['Genero', 'Casado', 'Dependents', 'PhoneService', 
                       'Servico_Internet', 'Servico_Seguranca', 'Suporte_Tecnico', 
                       'StreamingTV', 'Tipo_Contrato', 'PaymentMethod', 'Churn']

# Convertendo colunas do tipo 'object' (strings) para 'category'
for col in colunas_categoricas:
    df[col] = df[col].astype('category')

# Otimizando as colunas numéricas (Downcasting para economizar memória)
# 'Idoso' possui apenas valores 0 e 1, logo int8 (8 bits) é suficiente
df['Idoso'] = df['Idoso'].astype('int8')

# 'Tempo_como_Cliente' atinge no máximo em torno de 72 meses, logo int16 é perfeitamente adequado
df['Tempo_como_Cliente'] = df['Tempo_como_Cliente'].astype('int16')

# 3. Verificando o resultado e a redução no impacto na memória
print("\n--- Tipos de Dados e Uso de Memória (DEPOIS da Otimização) ---")
display(df.info())
# obs: comentários adicionados pós análise

--- Tipos de Dados e Uso de Memória (ANTES da Otimização) ---
<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2500 non-null   str
 1   Genero              2488 non-null   str
 2   Idoso               2500 non-null   int64
 3   Casado              2500 non-null   str
 4   Dependents          2500 non-null   str
 5   Tempo_como_Cliente  2500 non-null   int64
 6   PhoneService        1018 non-null   str
 7   Servico_Internet    2500 non-null   str
 8   Servico_Seguranca   2500 non-null   str
 9   Suporte_Tecnico     2500 non-null   str
 10  StreamingTV         2500 non-null   str
 11  Tipo_Contrato       2500 non-null   str
 12  PaymentMethod       2500 non-null   str
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2500 non-null   float64
 15  Churn               2495 non-null   str
dtypes: float64(2), int64(2), str(12)
memory usage: 312.6 KB

None

--- Tipos de Dados e Uso de Memória (DEPOIS da Otimização) ---
<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2500 non-null   str
 1   Genero              2488 non-null   category
 2   Idoso               2500 non-null   int8
 3   Casado              2500 non-null   category
 4   Dependents          2500 non-null   category
 5   Tempo_como_Cliente  2500 non-null   int16
 6   PhoneService        1018 non-null   category
 7   Servico_Internet    2500 non-null   category
 8   Servico_Seguranca   2500 non-null   category
 9   Suporte_Tecnico     2500 non-null   category
 10  StreamingTV         2500 non-null   category
 11  Tipo_Contrato       2500 non-null   category
 12  PaymentMethod       2500 non-null   category
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2500 non-null   float64
 15  Churn               2495 non-null   category
dtypes: category(11), float64(2), int16(1), int8(1), str(1)
memory usage: 93.2 KB

None

# 2 - Esse exercício faremos por etapas:
A) Verifique se temos colunas com dados faltantes e traga a % dos dados faltantes por coluna.

In [ ]:
# A) Verificando % de dados faltantes por coluna
percentual_faltantes = (df.isnull().sum() / len(df)) * 100

print("--- Percentual de Dados Faltantes (%) ---")
# Filtramos para exibir apenas colunas que possuem dados ausentes, ordenando de forma decrescente
display(percentual_faltantes[percentual_faltantes > 0].sort_values(ascending=False))

--- Percentual de Dados Faltantes (%) ---

PhoneService        59.28
Pagamento_Mensal    13.00
Genero               0.48
Churn                0.20
dtype: float64

B) Exclua nessa etapa as linhas das colunas com dados faltantes que você analisar que esse método é o ideal. Justifique o motivo de estar excluindo essas linhas.

In [ ]:
# Justificativa para exclusão de LINHAS:
# 1. Churn (0.20% faltantes): Sendo a NOSSA VARIÁVEL ALVO (Target), nós nunca devemos imputá-la. 
#    Fazer isso significa "inventar" a resposta para o modelo treinar, o que gera um viés gravíssimo.
# 2. Genero (0.48% faltantes): O percentual de perda é tão insignificante (< 1%) que compensa 
#    mais simplesmente descartar as linhas afetadas do que realizar uma imputação e possivelmente distorcer os dados.

# Removendo apenas as linhas onde 'Churn' ou 'Genero' são nulos
df.dropna(subset=['Churn', 'Genero'], inplace=True)

print("Dimensões do dataset após a remoção:", df.shape)

Dimensões do dataset após a remoção: (2488, 16)

C) Nessa etapa substitua pela média, mediana ou moda as linhas das colunas com valores faltantes que você analisou e entendeu que esse era o melhor método. Não se esqueça de justificar sua escolha.

**Dica variáveis numéricas:** Não se esqueça de verificar a distrbuição dos dados, média e mediana.

**Dica variáveis categóricas:** Caso precise substituir uma variável categórica utilize um gráfico de barras para verificar a que mais aparece e utilizar ela na substituição.
Ou você pode optar por excluir a coluna, mas justifique sua escolha.

Caso opte por substituir você pode utilizar a função fillna:
df['SUACOLUNA'].fillna("VALOR QUE SUBSTITUIRA O NULO", inplace=True)
Ela funcionará como a replace.

In [ ]:
# Justificativa para as ações em C:
# 1. PhoneService (Aprox 60% faltante): Quando a perda de dados é tão massiva, qualquer tentativa de imputação 
#    irá criar um pico artificial enorme e destruir a distribuição original. 
#    A prática ideal em Data Science neste cenário é EXCLUIR A COLUNA inteira.
# 2. Pagamento_Mensal (Aprox 13% faltante): Como é uma variável numérica contínua, usamos a MEDIANA.
#    Optamos pela mediana pois ela é uma medida de tendência central muito mais robusta contra 
#    valores discrepantes (outliers) do que a média.

# 1. Excluindo a coluna PhoneService que está irremediavelmente comprometida
df.drop(columns=['PhoneService'], inplace=True)

# 2. Preenchendo Pagamento_Mensal com a Mediana
mediana_pagamento = df['Pagamento_Mensal'].median()

# Usando o padrão moderno do Pandas 2.0+ (Copy-on-Write) sem o uso do inplace em fatias:
df['Pagamento_Mensal'] = df['Pagamento_Mensal'].fillna(mediana_pagamento)

# Verificação final para mostrar que nosso Dataset está limpo!
print("\nVerificação Final - Total de Nulos restantes no Dataset:")
display(df.isnull().sum().sum())

Verificação Final - Total de Nulos restantes no Dataset:

np.int64(0)

# 3 - Verifique se encontramos valores digitados incorretamente, ou com letras maiusculas ou minusculas, ou até mesmo mesmos valores porém escritos de forma dirente e corrija.

In [ ]:
# 3) Verificação e correção de valores digitados incorretamente

print("--- Valores com Erros de Digitação (Antes da Correção) ---")
display(df['Genero'].unique())
display(df['Servico_Internet'].unique())

# Corrigindo 'Genero' e 'Servico_Internet'
# Dica de ouro: Sempre converta para object antes de usar o replace em categorias para evitar erros no Pandas
df['Genero'] = df['Genero'].astype('object').replace({'F': 'Female', 'f': 'Female', 'M': 'Male'}).astype('category')
df['Servico_Internet'] = df['Servico_Internet'].astype('object').replace({'dsl': 'DSL'}).astype('category')

print("\n--- Valores Corrigidos (Depois) ---")
display(df['Genero'].unique())
display(df['Servico_Internet'].unique())

--- Valores com Erros de Digitação (Antes da Correção) ---

['Female', 'Male', 'F', 'M', 'f']
Categories (5, str): ['F', 'Female', 'M', 'Male', 'f']

['DSL', 'No', 'Fiber optic', 'dsl']
Categories (4, str): ['DSL', 'Fiber optic', 'No', 'dsl']

--- Valores Corrigidos (Depois) ---

['Female', 'Male']
Categories (2, str): ['Female', 'Male']

['DSL', 'No', 'Fiber optic']
Categories (3, str): ['DSL', 'Fiber optic', 'No']

# [EXTRA] 4 - Caso deseje, para manter um padrão na sua base, renomeie as colunas ou deixando em português, ou inglês.

In [ ]:
# [EXTRA] 4) Padronização e Tradução Completa do Dataset!

# 1. Traduzindo os nomes das Colunas restantes que estão em Inglês
dicionario_colunas = {
    'customerID': 'ID_Cliente',
    'Dependents': 'Dependentes',
    'PaymentMethod': 'Metodo_Pagamento',
    # Nota: A palavra "Churn" é um jargão universal da área de Dados no Brasil.
    # Optamos por mantê-la como 'Churn', mas se preferir, pode ser 'Evasao'.
}
df.rename(columns=dicionario_colunas, inplace=True)

# 2. Traduzindo as Categorias dentro das colunas! (Nível Avançado)
traducao_geral = {
    'Yes': 'Sim', 
    'No': 'Não',
    'No internet service': 'Sem internet',
    'Female': 'Feminino',
    'Male': 'Masculino',
    'Month-to-month': 'Mensal',
    'One year': 'Anual',
    'Two year': 'Bianual',
    'Electronic check': 'Cheque Eletrônico',
    'Mailed check': 'Cheque por Correio',
    'Bank transfer (automatic)': 'Transferência Bancária (Auto)',
    'Credit card (automatic)': 'Cartão de Crédito (Auto)'
}

# Selecionando colunas que contém texto/categorias
colunas_para_traduzir = df.select_dtypes(include=['category', 'object', 'str']).columns


# Aplicando o dicionário de tradução
for col in colunas_para_traduzir:
    if col != 'ID_Cliente': # Protegendo a coluna de IDs
        df[col] = df[col].astype('object').replace(traducao_geral).astype('category')

print("--- Dataframe Padronizado e 100% em Português ---")
display(df.head())

--- Dataframe Padronizado e 100% em Português ---

/tmp/ipykernel_49499/3872571028.py:30: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colunas_para_traduzir = df.select_dtypes(include=['category', 'object']).columns

,ID_Cliente,Genero,Idoso,Casado,Dependentes,Tempo_como_Cliente,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,Metodo_Pagamento,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Feminino,0,Sim,Não,1,DSL,Não,Não,Não,Mensal,Cheque Eletrônico,29.85,29.85,Não
1,5575-GNVDE,Masculino,0,Não,Não,34,DSL,Sim,Não,Não,Anual,Cheque por Correio,56.95,1889.50,Não
2,3668-QPYBK,Masculino,0,Não,Não,2,DSL,Sim,Não,Não,Mensal,Cheque por Correio,53.85,108.15,Sim
3,7795-CFOCW,Masculino,0,Não,Não,45,DSL,Sim,Sim,Não,Anual,Transferência Bancária (Auto),71.45,1840.75,Não
16,8191-XWSZG,Feminino,0,Não,Não,52,Não,Sem internet,Sem internet,Sem internet,Anual,Cheque por Correio,71.45,1022.95,Não